stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw_data
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw_data
    outs:
      - data/processed_data
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed_data
    outs:
      - data/feature_engineered_data
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/feature_engineered_data
    outs:
      - models/random_forest_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/random_forest_model.pkl
      - data/feature_engineered_data
    outs:
      - reports/metrics.json